require("config.options")
require("config.plugins")

require("extensions.ts_install")
require("extensions.powershell")
require("extensions.fidget")
require("extensions.mason")
require("extensions.mason_lspconfig")
require("extensions.mason_tool_installer")
require("extensions.treesitter")
require("extensions.treesitter_textobjects")
require("extensions.oil")

require("config.lsp")
require("config.keymaps")
require("config.autocmds")

require("extensions.undotree")
require("extensions.harpoon")
require("extensions.fugitive")
require("extensions.colors")
require("extensions.telescope")
require("extensions.cmp")
require("config.diagnostics")
require("extensions.trouble")
require("extensions.conform")
require("config.pack")
require("extensions.rfc")
require("extensions.license")
require("extensions.dadbod")
