#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find /Users /home ~/wb ~/ ~/personal ~/ctf-devel ~/software ~/software/git ~/software/libraries /mnt/storage /mnt/storage/iso /mnt/storage/books /mnt/storage/media -mindepth 1 -maxdepth 1 ! -name ".*" -type d,l 2>/dev/null | grep -v "/Users/Shared" | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

tmux switch-client -t "$selected_name"
